services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - core

  auth:
    build: ./services/auth
    expose:
      - "3000"

  core:
    build: ./services/core
    expose:
      - "4000"
